baseURL = "https://hypergraphwalk.com"
languageCode = "en-us"
title = "Hyper Graph Walk"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
paginate = 5

[Params]
  subtitle = "Code, Math, and other philosphies"
  logo = "img/avatar-icon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true


[Author]
  name = "Ronald Jordan"
  facebook = "ronald.jordan.969"
  github = "jron82"
  twitter = "rexwebdev"


[taxonomies]
  author = "authors"

[permalinks]
  posts = "/:title/"